(function(){if(typeof ncbi==="undefined")ncbi={};if(ncbi.sg)typeof console!=="undefined"&&console.error&&console.error("The logging JavaScript was added twice in the document. Please include it one time.");else{ncbi.sg=function(){};ncbi.sg.getInstance=function(){if(!ncbi.sg._instance)ncbi.sg._instance=new ncbi.sg;return ncbi.sg._instance};ncbi.sg._instance=null;ncbi.sg._version="24";(function(){var a=navigator.cookieEnabled?true:false;if(typeof navigator.cookieEnabled==="undefined"&&!a){document.cookie=
"testcookie";a=document.cookie.indexOf("testcookie")!==-1?true:false}ncbi.sg.isCookieEnabled=a})();ncbi.sg.appLogIgnore=["ncbi_sessionid","ncbi_clickdisabled"];ncbi.sg.prototype={init:function(){this.isProcessRunning=true;this._setUpMetaTagValues();this._setScrollingEnabled();if(this._cachedVals.ncbi_db&&this._cachedVals.ncbi_db.value.toLowerCase()=="pubmed"&&this._cachedVals.ncbi_report&&this._cachedVals.ncbi_report.value.toLowerCase()=="abstract"&&this._cachedVals.ncbi_resultcount&&this._cachedVals.ncbi_resultcount.value.toLowerCase()==
"1"||this._cachedVals.ncbi_db&&this._cachedVals.ncbi_db.value.toLowerCase()=="pmc"&&this._cachedVals.ncbi_report&&this._cachedVals.ncbi_report.value.toLowerCase()=="record"&&this._cachedVals.ncbi_type&&this._cachedVals.ncbi_type.value.toLowerCase()=="fulltext")ncbi.sg.isHoverEnabled=true;this._setUpPathParts();this._setUpCustomProps();this._addOnScrollListeners();this.send("init");this._sendPrev();this._addPrintPing();this._setBeforeScrollDetails()},_vals:{},_cachedVals:{},_hasInitRun:false,_pathParts:{part1:"",
part2:"",part3:"",part4:""},_setScrollingEnabled:function(){try{ncbi.sg.isScrollingEnabled=false;var a=ncbi.sgAppsWithScrolling;if(typeof a!=="undefined")for(var b=0;b<a.length;b++){var d=true,c=a[b];for(var f in c)if(!this._cachedVals[f]||this._cachedVals[f].value.toLowerCase()!=c[f]){d=false;break}if(d){ncbi.sg.isScrollingEnabled=true;break}}}catch(g){ncbi.sg.getInstance().noteEventData("jserror",{jserror:g.toString(),currenturl:window.location.href},["ncbi_sessionid","ncbi_phid"])}},_setUpMetaTagValues:function(){for(var a=
document.getElementsByTagName("meta"),b=0;b<a.length;b++){var d=a[b].name;d.indexOf("ncbi_")===0&&this.addEntry(d,a[b].content)}},_setUpCachedMetaTagValues:function(a){for(var b=0;b<a.length;b++){var d=this._cachedVals[a[b]];d&&this.addEntry(a[b],d.value)}},cachedNames:["ncbi_app","ncbi_db","ncbi_pcid","ncbi_pdid","ncbi_phid","ncbi_sessionid","ncbi_uidlist"],ignoreLengthRestrictions:["jserror","jserrorlocation"],addEntry:function(a,b){if(!(b===undefined||b.length===0)){if(b.length>100&&this.ignoreLengthRestrictions.indexOf(a)===
-1)b=b.substr(0,100);this._cachedVals[a]={sProp:a,value:b}}},removeAllEntries:function(){for(var a={},b=this.cachedNames.length,d=0;d<b;d++){var c=this.cachedNames[d],f=this._cachedVals[c];if(f)a[c]=f}this._cachedVals=a;for(var g in this._pathParts)this._pathParts[g]=""},_setUpCustomProps:function(){var a=this._pathParts.part1,b=this._pathParts.part2.length>0?":"+this._pathParts.part2:"",d=this._pathParts.part3.length>0?":"+this._pathParts.part3:"",c=this._pathParts.part4.length>0?":"+this._pathParts.part4:
"";a={pagename:a+b+d,server:window.location.hostname,sitesect2:a+b,subsect3:a+b+d,subsect4:a+b+d+c,heir1:(a+b+d+c).replace(/:/g,"|")};for(var f in a)this.addEntry(f,a[f]);this._sessionIdCheck();this._staticPageCheck();this._prevHitCheck();this._browserConfigurationSettings();this._hashCheck()},_staticPageCheck:function(){this._cachedVals.ncbi_app&&this._cachedVals.ncbi_app.value.length>0||this.addEntry("ncbi_app","static");this._cachedVals.ncbi_pdid&&this._cachedVals.ncbi_pdid.value.length>0||this.addEntry("ncbi_pdid",
(document.title||"unknown").replace(/\s+/g,""))},_sessionIdCheck:function(){if(!(this._cachedVals.ncbi_sessionid&&this._cachedVals.ncbi_sessionid.value.length>0)){var a="";if(a.length===0){var b=this.getCookie("WebCubbyUser")||this.getCookie("WebEnv");if(b.length>0){b=unescape(b).split("@");if(b.length>1)a=b[b.length-1]}}if(a.length===0)a="NOSESSIONID";this.addEntry("ncbi_sessionid",a)}},getBrowserWidthHeight:function(){var a=this.getViewportWidth(),b=this.getViewportHeight();return{width:a,height:b}},
_browserConfigurationSettings:function(){var a=this.getBrowserWidthHeight();this.addEntry("browserwidth",a.width);this.addEntry("browserheight",a.height);this.addEntry("screenwidth",screen.width);this.addEntry("screenheight",screen.height);this.addEntry("screenavailwidth",screen.availWidth);this.addEntry("screenavailheight",screen.availHeight);if(document&&document.body){var b=document.body.scrollWidth,d=document.body.scrollHeight,c=d>a.height?"true":"false";this.addEntry("canscroll_x",b>a.width?
"true":"false");this.addEntry("canscroll_y",c);this.addEntry("scrollwidth",b);this.addEntry("scrollheight",d)}if(screen.colorDepth)this.addEntry("colorDepth",screen.colorDepth);else screen.pixelDepth&&this.addEntry("colorDepth",screen.pixelDepth)},_hashCheck:function(){var a=window.location.hash;if(a){a=a.replace("#","");this.addEntry("urlhash",a)}(a=window.location.search.match(/[?&]campaign=([^&]*)/))&&this.addEntry("campaign",a[1])},_createPHID:function(){var a=this._cachedVals.ncbi_sessionid.value,
b=a.substr(0,15)+"9"+(new Date).getTime().toString(),d=a.length;b+=a.substr(d-(32-b.length),d);a={value:b};this.addEntry("ncbi_phid",b);return a},currentPageHitId:null,_prevHitCheck:function(){var a=this.getCookie("ncbi_prevPHID"),b=this._cachedVals.ncbi_phid;a.length>0&&this.addEntry("prev_phid",a);if(!b||!b.value||b.value.length===0)b=this._createPHID();this.currentPageHitId=b.value;var d=this;ncbi.sg._hasFocus&&d.setCookie("ncbi_prevPHID",b.value);var c=window.onfocus;window.onfocus=function(f){d.getCookie("ncbi_prevPHID")!==
b.value&&d.setCookie("ncbi_prevPHID",b.value);typeof c==="function"&&c(f)}},_setUpPathParts:function(){var a=this._cachedVals.ncbi_app,b=this._cachedVals.ncbi_db,d=this._cachedVals.ncbi_pdid,c=this._cachedVals.ncbi_pcid;this._pathParts.part1=a!==undefined?a.value:"";this._pathParts.part2=b!==undefined?b.value:"";this._pathParts.part3=d!==undefined?d.value:"";this._pathParts.part4=c!==undefined?c.value:""},getPerfStats:function(){var a=window.performance;if(!a)return{};var b=a.timing;if(b)b={dns:b.domainLookupEnd-
b.domainLookupStart,connect:b.connectEnd-b.connectStart,ttfb:b.responseStart-b.connectEnd,basePage:b.responseEnd-b.responseStart,frontEnd:b.loadEventStart-b.responseEnd};else return{};if(a=a.navigation){b.navType=a.type;b.redirectCount=a.redirectCount}return b},setPerfStats:function(a,b){var d=this.getPerfStats();for(var c in d){var f=d[c];if(f>=0){var g="jsperf_"+c;if(b)a[g]=f;else a.push(g+"="+f)}}},send:function(a,b){var d=[];if(a==="init"){d.push("jsevent=render");ncbi.sg.renderTime=new Date;
if(typeof ncbi_startTime!=="undefined"){d.push("jsrendertime="+(ncbi.sg.renderTime-ncbi_startTime));ncbi.sg.loadTime&&d.push("jsloadtime="+(ncbi.sg.loadTime-ncbi_startTime))}this.setPerfStats(d);d.push("cookieenabled="+(ncbi.sg.isCookieEnabled?"true":"false"))}for(var c in this._cachedVals)ncbi.sg.appLogIgnore.indexOf(c)===-1&&d.push(c+"="+encodeURIComponent(this._cachedVals[c].value));this.sendAl(d.join("&"),b,true);this._hasInitRun=true;var f=this;setTimeout(function(){f.isProcessRunning=false;
f.runSGProcess()},300)},_sendPrev:function(){var a=ncbi.sg.getInstance(),b=a.getCookie("clicknext");if(b){ncbi.sg.ping(b);a.setCookie("clicknext","")}if(b=a.getCookie("prevsearch")){ncbi.sg.ping(b);a.setCookie("prevsearch","")}if(b=a.getCookie("unloadnext")){ncbi.sg.ping(b);a.setCookie("unloadnext","")}},sendAl:function(a,b,d){if(a.indexOf("jseventms")===-1)a+="&jseventms="+ncbi.sg.getInstance().getMillisecondsSinceSunday();a.match(/jsevent=search/i)&&this.setCookie("prevsearch",a.replace(/jsevent=search(next)?/i,
"jsevent=searchnext"),null);a+="&sgVersion="+ncbi.sg._version;var c=window.location.port?":"+window.location.port:"";reqURL=typeof __ncbi_stat_url!=="undefined"?__ncbi_stat_url+"?"+a:window.location.protocol+"//"+window.location.hostname+c+"/stat?"+a;this.makeAjaxCall(reqURL,function(){typeof b==="function"&&b()},d)},_processingQueue:[],isProcessRunning:false,addSGProcess:function(a){this._processingQueue.push(a)},getSGProcess:function(a){return this._processingQueue.shift(a)},runSGProcess:function(){if(this.isProcessRunning||
this._processingQueue.length===0||!this._hasInitRun)return false;this.isProcessRunning=true;this.removeAllEntries();var a=this.getSGProcess();this._setUpCachedMetaTagValues(a.metadata);this.addEntry("jsevent",a.eventName);for(var b in a.props)this.addEntry(b,a.props[b]);this.send(a.eventName,a.callbackFnc);var d=this;setTimeout(function(){d.isProcessRunning=false;d.runSGProcess()},300)},noteEventData:function(a,b,d,c){this.addSGProcess({eventName:a,props:b,metadata:d,callback:c});this.runSGProcess()},
setCookie:function(a,b,d){if(window.sessionStorage)try{sessionStorage.setItem(a,b)}catch(c){}var f=new Date;d!==null&&f.setDate(f.getDate()+d);document.cookie=a+"="+escape(b)+(d===null?"":"; expires="+f.toGMTString())+"; domain="+escape(".nih.gov")+"; path=/"},getCookie:function(a){var b;if(window.sessionStorage){try{b=sessionStorage.getItem(a)||""}catch(d){b=""}if(b.length>0)return b}if(document.cookie.length>0){b=document.cookie.indexOf(a+"=");if(b!==-1){b=b+a.length+1;a=document.cookie.indexOf(";",
b);if(a===-1)a=document.cookie.length;return unescape(document.cookie.substring(b,a))}}return""},getTransport:function(){var a=null;if(window.XMLHttpRequest)try{a=new XMLHttpRequest;this.getTransport=function(){return new XMLHttpRequest}}catch(b){a=null}if(window.ActiveXObject&&a===null)try{a=new ActiveXObject("Msxml2.XMLHTTP");this.getTransport=function(){return new ActiveXObject("Msxml2.XMLHTTP")}}catch(d){try{a=new ActiveXObject("Microsoft.XMLHTTP");this.getTransport=function(){return new ActiveXObject("Microsoft.XMLHTTP")}}catch(c){a=
false}}if(a===null)this.getTransport=function(){return null};return this.getTransport()},makeAjaxCall:function(a,b,d){var c=this.getTransport();c.open("GET",a,d);if(d)c.onreadystatechange=function(){c.readyState===4&&b(c)};ncbi.sg.lastPing=c;c.send(null);return c},scrollDetails:{maxScroll_x:0,maxScroll_y:0,currScroll_x:0,currScroll_y:0,hasScrolled:false},scrollEventDetails:{xTenths:0,yTenths:0,xMax:0,yMax:0},_getScrollXYPx:function(){return[window.pageXOffset||document.documentElement.scrollLeft||
document.body.scrollLeft||0,window.pageYOffset||document.documentElement.scrollTop||document.body.scrollTop||0]},_getScrollXY:function(){var a=this.getViewportHeight(),b=this.getViewportWidth(),d=document.body.scrollHeight,c=document.body.scrollWidth,f=this._getScrollXYPx(),g=Math.round(f[1]/a*10)/10;return{xRel:Math.round(f[0]/b*10)/10,yRel:g,viewportHeight:a,viewportWidth:b,pageHeight:d,pageWidth:c}},_addOnScrollListeners:function(){var a=window.onscroll,b=this;window.onscroll=function(){if(ncbi.sg.isScrollingEnabled){b._setScrollDetails();
b.scrollDetails.hasScrolled=true;b._addScrollEvent()}else{b._setScrollDetails();b.scrollDetails.hasScrolled=true}if(typeof a==="function")return a()}},getViewportHeight:function(){return window.innerHeight?window.innerHeight:document.documentElement&&document.documentElement.clientHeight?document.documentElement.clientHeight:document.body!==null?document.body.clientHeight:"NA"},getViewportWidth:function(){return window.innerWidth?window.innerWidth:document.documentElement&&document.documentElement.clientWidth?
document.documentElement.clientWidth:document.body!==null?document.body.clientWidth:"NA"},_setScrollDetails:function(){this.scrollDetails.currScroll_y=window.pageYOffset||document.documentElement.scrollTop||document.body.scrollTop||0;this.scrollDetails.currScroll_x=window.pageXOffset||document.documentElement.scrollLeft||document.body.scrollLeft||0;this.getViewportWidth();this.getViewportHeight();if(this.scrollDetails.maxScroll_y<this.scrollDetails.currScroll_y)this.scrollDetails.maxScroll_y=this.scrollDetails.currScroll_y;
if(this.scrollDetails.maxScroll_x<this.scrollDetails.currScroll_x)this.scrollDetails.maxScroll_x=this.scrollDetails.currScroll_x},isVisible:function(a){var b=this.findEffectiveStyleProperty(a,"visibility");a=this._isDisplayed(a);return b!="hidden"&&a},_isDisplayed:function(a){if(this.findEffectiveStyleProperty(a,"display")=="none")return false;if(a.parentNode.style)return this._isDisplayed(a.parentNode);return true},findEffectiveStyleProperty:function(a,b){var d=this.findEffectiveStyle(a)[b];if(d==
"inherit"&&a.parentNode.style)return this.findEffectiveStyleProperty(a.parentNode,b);return d},findEffectiveStyle:function(a){if(a.style!=undefined){if(window.getComputedStyle)return window.getComputedStyle(a,null);if(a.currentStyle)return a.currentStyle;if(window.document.defaultView&&window.document.defaultView.getComputedStyle)return window.document.defaultView.getComputedStyle(a,null);return null}},findElementPos:function(a,b,d){var c=0,f=0;if(a.offsetLeft)c+=parseInt(a.offsetLeft);if(a.offsetTop)f+=
parseInt(a.offsetTop);if(a.scrollTop&&a.scrollTop>0){f-=parseInt(a.scrollTop);d=true}if(a.scrollLeft&&a.scrollLeft>0){c-=parseInt(a.scrollLeft);b=true}if(a.offsetParent){b=this.findElementPos(a.offsetParent,b,d);if(b==-1)return-1;c+=b[0];f+=b[1]}else if(a.ownerDocument){var g=a.ownerDocument.defaultView;if(!g&&a.ownerDocument.parentWindow)g=a.ownerDocument.parentWindow;if(g){var m=g.pageXOffset!==undefined?g.pageXOffset:(a.document.documentElement||a.document.body.parentNode||a.document.body).scrollLeft;
a=g.pageYOffset!==undefined?g.pageYOffset:(a.document.documentElement||a.document.body.parentNode||a.document.body).scrollTop;if(!d&&a&&a>0)f-=parseInt(a);if(!b&&m&&m>0)c-=parseInt(m);if(g.frameElement){b=this.findElementPos(g.frameElement);if(b==-1)return-1;c+=b[0];f+=b[1]}}}return[c,f]},addObjData:function(a,b){for(var d in b)a[d]=b[d]},getJoinedData:function(a){var b=[];for(var d in a)b.push(d+"="+encodeURIComponent(a[d]));return b.join("&")},addScrollHeadingData:function(a,b){var d=this.scrollEventDetails.headings;
if(d){a["numHeadings."+this._scrollOrder+".scrollInfo"]=d.length;for(var c=0;c<d.length;c++){var f=d[c];if(f.visible){var g={};if(f.innerText)g["innerText."+f.index+".headings."+this._scrollOrder+".scrollInfo"]=f.innerText;if(f.id)g["id."+f.index+".headings."+this._scrollOrder+".scrollInfo"]=f.id;g["tagName."+f.index+".headings."+this._scrollOrder+".scrollInfo"]=f.tagName;b=b?b:1800;this.getJoinedData(a).length+this.getJoinedData(g).length<b&&this.addObjData(a,g)}}}return a},getVisibleHeadings:function(){for(var a=
[],b=document.getElementsByTagName("*"),d=-1,c=0;c<b.length;c++){for(var f=b[c],g=false,m=f.tagName.toLowerCase(),j=0;j<7;j++)if(m=="h"+j)g=true;if(g){d+=1;j=this.findElementPos(f);g=j[1];j=j[0];var y=f.offsetHeight,F=f.offsetWidth,z=this.getViewportHeight(),C=this.getViewportWidth(),x={},t=f.getAttribute("id")||f.id;if(t)x.id=t;if(t=(f.getAttribute("innerText")||f.innerText||f.getAttribute("textContent")||f.textContent).replace(/^\s+|\s+$/g,""))x.innerText=t.substring(0,50);x.index=d;x.tagName=m;
if(g+y>=0&&g<=z&&j+F>=0&&j<=C)if(this.isVisible(f)){x.visible=true;a.push(x)}}}return a},_setBeforeScrollDetails:function(a){this._lastScroll=a?a:null;a=this._getScrollXY();var b=a.yRel;this.scrollEventDetails.xTenths=Math.round(a.xRel*10);this.scrollEventDetails.yTenths=Math.round(b*10);this.scrollEventDetails.xMax=Math.max(this.scrollEventDetails.xTenths,this.scrollEventDetails.xMax);this.scrollEventDetails.yMax=Math.max(this.scrollEventDetails.yTenths,this.scrollEventDetails.yMax);this.scrollEventDetails.headings=
this.getVisibleHeadings()},getScrollDetails:function(a,b){if(!ncbi.sg.isScrollingEnabled){this._setScrollDetails();return this.scrollDetails}var d=this.scrollEventDetails;d.tstamp=(new Date).getTime();var c=this._getScrollXY(),f=null;if(b||!this._lastScroll||d.tstamp-this._lastScroll>1E3){this._scrollOrder=this._scrollOrder!=undefined?this._scrollOrder+1:0;b="yTenths."+this._scrollOrder+".scrollInfo";f="xTenths."+this._scrollOrder+".scrollInfo";var g="maxXTenths."+this._scrollOrder+".scrollInfo",
m="maxYTenths."+this._scrollOrder+".scrollInfo",j={};j["duration."+this._scrollOrder+".scrollInfo"]=this._lastScroll?d.tstamp-this._lastScroll:new Date-ncbi.sg.loadTime;j[f]=this.scrollEventDetails.xTenths;j[b]=this.scrollEventDetails.yTenths;j[g]=this.scrollEventDetails.xMax;j[m]=this.scrollEventDetails.yMax;j["viewportHeight."+this._scrollOrder+".scrollInfo"]=c.viewportHeight;j["viewportWidth."+this._scrollOrder+".scrollInfo"]=c.viewportWidth;j["maxPossibleScrollTenthsY."+this._scrollOrder+".scrollInfo"]=
Math.round((c.pageHeight/c.viewportHeight-1)*10);j["maxPossibleScrollTenthsX."+this._scrollOrder+".scrollInfo"]=Math.round((c.pageWidth/c.viewportWidth-1)*10);f=j=this.addScrollHeadingData(j,a)}this._setBeforeScrollDetails(d.tstamp);return f},getScrollDetailsAr:function(a,b){var d=[];a=this.getScrollDetails(a,b);for(var c in a)d.push(c+"="+encodeURIComponent(a[c]));return d},addScrollDetailsAr:function(a,b,d){b=this.getScrollDetailsAr(b,d);for(d=0;d<b.length;d++)a.push(b[d])},addScrollDetails:function(a,
b,d){b=this.getScrollDetails(b,d);for(var c in b)a[c]=b[c]},trimScrollDetails:function(){},_addScrollEvent:function(){try{var a=this.getScrollDetails();if(a){a.jsevent="scroll";ncbi.sg.ping(a)}}catch(b){ncbi.sg.getInstance().noteEventData("jserror",{jserror:b.toString(),currenturl:window.location.href},["ncbi_sessionid","ncbi_phid"])}},_addPrintPing:function(){function a(){var c=document.createElement("style");c.type="text/css";var f=document.createElement("style");f.type="text/css";f.media="print";
for(var g=["jsevent=print"],m=0;m<b.cachedNames.length;m++){var j=b.cachedNames[m],y=b._cachedVals[j];y&&j!=="ncbi_sessionid"&&g.push(j+"="+encodeURIComponent(y.value))}g=".print-log { position:absolute;left:-10000px;top:auto;width:1px;height:1px;overflow:hidden; }.print-log li { list-style-image: url('/stat?"+g.join("&")+"'); }";if(f.styleSheet){f.styleSheet.cssText=g;c.styleSheet.cssText=".print-log { position:absolute;left:-10000px;top:auto;width:1px;height:1px;overflow:hidden; }"}else{f.appendChild(document.createTextNode(g));
c.appendChild(document.createTextNode(".print-log { position:absolute;left:-10000px;top:auto;width:1px;height:1px;overflow:hidden; }"))}g=document.getElementsByTagName("head")[0];g.appendChild(f);g.appendChild(c);c=document.createElement("ul");c.className="print-log";f=document.createElement("li");c.appendChild(f);document.body.appendChild(c)}var b=this;if(typeof jQuery!=="undefined")jQuery(a);else{var d=window.onload;window.onload=function(c){d&&d(c);a()}}},getMillisecondsSinceSunday:function(){var a=
new Date,b=new Date;b.setDate(b.getDate()-b.getDay());b.setHours(0);b.setMinutes(0);b.setSeconds(0);b.setMilliseconds(0);return(a-b).toString(36)}};ncbi.sg.lastPing=null;ncbi.sg.hasNotedErrorEvent=false;(function(){function a(){ncbi.sg.getInstance().setCookie("ncbi_prevPHID",ncbi.sg.getInstance().currentPageHitId);if(t.length>0)for(;t.length>0;)c(t.pop());var e={jsevent:"unload",ncbi_pingaction:"unload"};if(typeof ncbi_startTime!=="undefined"){e.ncbi_timeonpage=new Date-ncbi_startTime;if(typeof ncbi_onloadTime!==
"undefined"&&ncbi_onloadTime)e.ncbi_onloadTime=ncbi_onloadTime-ncbi_startTime}var h=ncbi.sg.getInstance();h.setPerfStats(e,true);h.addScrollDetails(e,1800-h.getJoinedData(e).length,true);if(!o){ncbi.sg.ping(e);var i="";for(var l in e)i+=l+"="+(l==="jsevent"?"unloadnext":e[l])+"&";i+="ncbi_phid="+h.currentPageHitId;h.setCookie("unloadnext",i,null)}o=true}function b(e){if(e){if(e.onclick)e.onclick_=e.onclick;if(e.oncontextmenu)e.oncontextmenu_=e.oncontextmenu}}function d(e){for(var h=t.length-1;h>=
-1;h--)if(t[h]===e){t.slice(h,1);break}c(e)}function c(e,h){if(w.indexOf(e.tstamp)===-1){w.push(e.tstamp);u.push(e);f("click",e,h)}}function f(e,h,i){var l=e==="click"?"link":"elem",k=h.link,s=h.evt,p=k.id||"",q=k.name||"",I=k.sid||"",G=k.href||"",A=k.innerText||k.textContent||"";if(A.length>50)A=A.substr(0,50);var D=k.getAttribute?k.getAttribute("ref")||k.ref||"":"",E=k.className?k.className.replace(/^\s?/,"").replace(/\s?$/,"").split(/\s/g).join(",")||"":"";h=[];var H=[],v=k.parentNode;if(v)for(var r=
0;r<6&&v!==null;r++){(parId=v.id)&&h.push(parId);if(parClassName=v.className)H=H.concat(parClassName.split(/\s/));v=v.parentNode}v=ncbi.sg.getInstance();r=v.currentPageHitId||"";var n=[];p.length>0&&n.push(l+"_id="+encodeURIComponent(p));q.length>0&&n.push(l+"_name="+encodeURIComponent(q));I.length>0&&n.push(l+"_sid="+encodeURIComponent(I));G.length>0&&n.push(l+"_href="+encodeURIComponent(G));A.length>0&&n.push(l+"_text="+encodeURIComponent(A));E.length>0&&n.push(l+"_class="+encodeURIComponent(E));
r=v.getBrowserWidthHeight();r.width!==null&&n.push("browserwidth="+encodeURIComponent(r.width));r.height!==null&&n.push("browserheight="+encodeURIComponent(r.height));for(var J in s){r=s[J];r!==undefined&&n.push(J.toLowerCase()+"="+r.toString())}n.push("jsevent="+e);D.length>0&&n.push(D);if(typeof jQuery!=="undefined")if(k=jQuery(k).attr("sg")){k=k.split(/\}\s*,\s*\{/);for(r=0;r<k.length;r++){s=k[r].match(/name\s*:\s*'(.+)',\s*selector\s*:\s*'(.+)'/);if(s.length===3){J="cust_"+s[1];s=jQuery(s[2]).val();
n.push(J+"="+encodeURIComponent(s))}}}if(i&&i.length>0)for(;i.length>0;)n.push(i.shift());h.length>0&&n.push("ancestorId="+h.join(","));H.length>0&&n.push("ancestorClassName="+H.join(",").replace(/\s+/g," ").replace(/(^\s|\s$)/g,""));v.addScrollDetailsAr(n,1800-n.join("&").length,true);if(e==="click"){e=n.join("&").replace("jsevent=click","jsevent=clicknext");r=ncbi.sg.getInstance().currentPageHitId||"";e+="&ncbi_phid="+r;v.setCookie("clicknext",e,null)}ncbi.sg.ping(n,true)}function g(e){var h={};
if(e){if(e.clientX||e.clientY){var i=ncbi.sg.getInstance()._getScrollXYPx();h.evt_coor_x=e.clientX+i[0];h.evt_coor_y=e.clientY+i[1]}else if(e.pageX||e.pageY){h.evt_coor_x=e.pageX;h.evt_coor_y=e.pageY}h.jseventms=ncbi.sg.getInstance().getMillisecondsSinceSunday()}return h}function m(e,h,i){function l(p,q,I,G){function A(H){for(var v=[function(n){if(typeof n.preventDefault==="undefined")n.preventDefault=function(){this.returnValue=false};if(typeof n.stopPropagation==="undefined")n.stopPropagation=function(){this.cancelBubble=
true};return n}(p)],r=0;r<I.length;r++)v.push(I[r]);E=q[H].apply(q,v)}ncbi.sg.getInstance().setCookie("ncbi_prevPHID",ncbi.sg.getInstance().currentPageHitId);var D=g(p);D.iscontextmenu=G==="contextmenu"?"true":"false";D={evt:D,link:q,tstamp:(new Date).getTime(),floodTstamp:(new Date).getTime()};d(D);ncbi.sg.clickTimers&&window.clearTimeout(ncbi.sg.clickTimers);ncbi.sg.clickTimers=window.setTimeout(function(){ncbi.sg.clickTimers=null},300);var E=null;if(G==="click"&&typeof q.onclick_==="function")A("onclick_");
else G==="contextmenu"&&typeof q.oncontextmenu_==="function"&&A("oncontextmenu_");if(E!==null||E!==undefined)return E}for(var k=0;k<10&&h<i;k++){var s=e[h];if(s&&!s._sg){s._sg=true;b(s);s.onclick=function(p){var q=null;q=l(p||window.event,this,arguments,"click");if(q!==null||q!==undefined)return q};s.oncontextmenu=function(p){var q=null;q=l(p||window.event,this,arguments,"contextmenu");if(q!==null||q!==undefined)return q}}h++}h<i&&window.setTimeout(function(){m(e,h,i)},0)}function j(e){for(var h=
[],i=0;i<e.length;i++)h.push(e[i]);return h}function y(){if(ncbi.sg.isClickEnabled){var e=j(document.links);m(e,0,e.length);e=j(document.getElementsByTagName("button"));m(e,0,e.length);e=[];if(typeof jQuery!=="undefined")e=j(jQuery("input[type=button], input[type=submit], input[type=reset]").get());else{var h=j(document.getElementsByTagName("input"));e=[];for(var i=h.length-1;i>=0;){var l=h[i],k=l.type;if(k==="button"||k==="submit"||k==="reset")e.push(l);i--}}e.length>0&&m(e,0,e.length)}}function F(e,
h,i,l){var k={},s=null,p=null;if(typeof h==="string"){s=h;p=i}else{k=g(h);s=i;p=l}if(p){h=typeof p;if(h==="string")p=[p];else if(h==="object"&&!(p instanceof Array)){h=[];for(var q in p)h.push(q+"="+p[q]);p=h}}ncbi.sg.sendElementEvent(s,{link:e,evt:k},p)}function z(e,h){var i=[];if(typeof h==="undefined")h=true;if(typeof e==="object"&&!(e instanceof Array))for(var l in e)i.push(l+"="+encodeURIComponent(e[l]));else if(typeof e==="string")i.push(e);else i=e;e=ncbi.sg.getInstance().currentPageHitId||
"";l=null;if(typeof ncbi.sg.loadTime!=="undefined")l=new Date-ncbi.sg.loadTime;var k=i.join("&");if(k.indexOf("jsevent=clicknext")!==-1||k.indexOf("jsevent=searchnext")!==-1||k.indexOf("jsevent=unloadnext")!==-1){e.length>0&&i.push("next_phid="+encodeURIComponent(e));l!==null&&i.push("next_ncbi_timesinceload="+l)}else{e.length>0&&i.push("ncbi_phid="+encodeURIComponent(e));l!==null&&i.push("ncbi_timesinceload="+l)}ncbi.sg.getInstance().sendAl(i.join("&"),null,h)}var C=window.onerror;window.onerror=
function(e,h,i){if(!ncbi.sg.hasNotedErrorEvent){ncbi.sg.getInstance().noteEventData("jserror",{jserror:e,jserrorlocation:h,jserrorline:i,currenturl:window.location.href},["ncbi_sessionid","ncbi_phid"]);ncbi.sg.hasNotedErrorEvent=true;if(typeof C==="function")return C(e,h,i)}};var x=window.onbeforeunload;window.onbeforeunload=function(e){a();if(typeof x==="function")return x(e)};var t=[],w=[],u=[],o=false;ncbi.sg.sendElementEvent=f;ncbi.sg.clickTimers=[];if(typeof ncbi.sg.isClickEnabled==="undefined"){for(var B=
document.getElementsByTagName("meta"),K=B.length-1,L=true;K>=0;){if(B[K].name.toLowerCase()==="ncbi_clickdisabled"){L=B[K].content.toLowerCase()==="false";break}K--}ncbi.sg.isClickEnabled=L}y();ncbi.sg.scanLinks=function(e){if(e){if(typeof e==="object"&&!(e instanceof Array))e=[e];m(e,0,e.length)}else y()};ncbi.sg.ping=function(e,h,i,l){typeof e==="undefined"||e===null||(typeof e==="object"&&e.nodeName!==undefined?F(e,h,i,l):z(e,h))};ncbi.sg.loadTime=new Date})();if(!Array.prototype.indexOf)Array.prototype.indexOf=
function(a,b){var d=this.length>>>0;b=Number(b)||0;b=b<0?Math.ceil(b):Math.floor(b);if(b<0)b+=d;for(;b<d;b++)if(b in this&&this[b]===a)return b;return-1};(function(){function a(){ncbi_onloadTime=new Date}ncbi_onloadTime=null;if(typeof jQuery!=="undefined")jQuery(window).load(a);else{var b=window.onload;window.onload=function(d){b&&b(d);a()}}})()}})();
jQuery&&jQuery(function(){if(ncbi.sg.isHoverEnabled){var a=function(c,f){var g=[];if(typeof f==="undefined")f=true;if(typeof c==="object"&&!(c instanceof Array))for(var m in c)g.push(m+"="+encodeURIComponent(c[m]));else if(typeof c==="string")g.push(c);else g=c;c=ncbi.sg.getInstance().currentPageHitId||"";m=null;if(typeof ncbi.sg.loadTime!=="undefined")m=new Date-ncbi.sg.loadTime;g.join("&");c.length>0&&g.push("next_phid="+encodeURIComponent(c));m!==null&&g.push("next_ncbi_timesinceload="+m);ncbi.sg.getInstance().sendAl(g.join("&"),
null,f)},b=ncbi.sg.getInstance().getCookie("hovernext");if(b){a(b);ncbi.sg.getInstance().setCookie("hovernext","")}var d=function(c){var f={};if(c){if(c.clientX||c.clientY){var g=ncbi.sg.getInstance()._getScrollXYPx();f.evt_coor_x=c.clientX+g[0];f.evt_coor_y=c.clientY+g[1]}else if(c.pageX||c.pageY){f.evt_coor_x=c.pageX;f.evt_coor_y=c.pageY}f.jseventms=ncbi.sg.getInstance().getMillisecondsSinceSunday()}return f};jQuery(document).on("mousedown","a[ref*='itool=Abstract-nondef'], #disc_col a",function(c){c=
c.originalEvent;var f=d(c);jQuery(c.target);(new Date).getTime();(new Date).getTime();var g=jQuery(c.target),m=g.id||"",j=g.name||"",y=g.sid||"",F=g.href||"",z=g.innerText||g.textContent||"";if(z.length>50)z=z.substr(0,50);var C=g.getAttribute?g.getAttribute("ref")||g.ref||"":"",x=g.className?g.className.replace(/^\s?/,"").replace(/\s?$/,"").split(/\s/g).join(",")||"":"";c=[];var t=[],w=g.parentNode;if(w)for(var u=0;u<6&&w!==null;u++){(parId=w.id)&&c.push(parId);if(parClassName=w.className)t=t.concat(parClassName.split(/\s/));
w=w.parentNode}w=ncbi.sg.getInstance();var o=w.currentPageHitId||"";o=[];m.length>0&&o.push("link_id="+encodeURIComponent(m));j.length>0&&o.push("link_name="+encodeURIComponent(j));y.length>0&&o.push("link_sid="+encodeURIComponent(y));F.length>0&&o.push("link_href="+encodeURIComponent(F));z.length>0&&o.push("link_text="+encodeURIComponent(z));x.length>0&&o.push("link_class="+encodeURIComponent(x));u=w.getBrowserWidthHeight();u.width!==null&&o.push("browserwidth="+encodeURIComponent(u.width));u.height!==
null&&o.push("browserheight="+encodeURIComponent(u.height));for(var B in f){u=f[B];u!==undefined&&o.push(B.toLowerCase()+"="+u.toString())}o.push("jsevent=hovernext");C.length>0&&o.push(C);if(typeof jQuery!=="undefined")if(f=jQuery(g).attr("sg")){f=f.split(/\}\s*,\s*\{/);for(u=0;u<f.length;u++){g=f[u].match(/name\s*:\s*'(.+)',\s*selector\s*:\s*'(.+)'/);if(g.length===3){B="cust_"+g[1];g=jQuery(g[2]).val();o.push(B+"="+encodeURIComponent(g))}}}c.length>0&&o.push("ancestorId="+c.join(","));t.length>
0&&o.push("ancestorClassName="+t.join(",").replace(/\s+/g," ").replace(/(^\s|\s$)/g,""));w.addScrollDetailsAr(o,1800-o.join("&").length,true);c=o.join("&");o=ncbi.sg.getInstance().currentPageHitId||"";c+="&ncbi_phid="+o;ncbi.sg.getInstance().setCookie("hovernext",c,null)});jQuery(document).on("mouseup mousedown",function(c){!jQuery(c.target).is("a[ref*='itool=Abstract-nondef']")&&jQuery(c.target).parents("a[ref*='itool=Abstract-nondef']").length==0&&!jQuery(c.target).is("#disc_col a")&&jQuery(c.target).parents("#disc_col a").length==
0&&ncbi.sg.getInstance().setCookie("hovernext","")})}});

;
// This code creates window.console if it doesn't exist.
// It also creates stub functions for those functions that are missing in window.console.
// (Safari implements some but not all of the firebug window.console methods--this implements the rest.)
(function() {
    var names = [ "log", "debug", "info", "warn", "error", "assert", "dir", "dirxml", "group",
                  "groupEnd", "time", "timeEnd", "count", "trace", "profile", "profileEnd" ];

    if (typeof(console) === 'undefined' || typeof console === "function" ) {
      //"typeof function" is needed see PP-769 
      console = {};
    }

    for (var i = 0; i < names.length; ++i) {
       if (typeof(console[names[i]]) === 'undefined') {
          console[names[i]] = function() { return false; };
       }
    }
    ncbi.sg.getInstance().init();                          
})();
