var OX_0daa6395 = '';
OX_0daa6395 += "<"+"script type=\'text/javascript\'><"+"!--//<"+"![CDATA[\n";
OX_0daa6395 += "if (navigator.appName == \"Microsoft Internet Explorer\") {\n";
OX_0daa6395 += "var windowheight = window.document.documentElement.clientHeight;\n";
OX_0daa6395 += "} else {\n";
OX_0daa6395 += "var windowheight = window.innerHeight;\n";
OX_0daa6395 += "}\n";
OX_0daa6395 += "var loaded = false;\n";
OX_0daa6395 += "var toscr = document.getElementById(\"advert-offset\").offsetTop + document.getElementById(\"article-navigation-bar\").offsetTop - windowheight;\n";
OX_0daa6395 += "function pgload() {\n";
OX_0daa6395 += "var pgadspace = document.getElementById(\"article-body\").offsetTop+document.getElementById(\"article-body\").offsetHeight-document.getElementById(\"advert-offset\").offsetTop-document.getElementById(\"article-navigation-bar\").offsetTop;\n";
OX_0daa6395 += "if (loaded == false && pgadspace>580) {\n";
OX_0daa6395 += "var scrpos = (window.pageYOffset || document.body.scrollTop || document.documentElement.scrollTop);\n";
OX_0daa6395 += "if (scrpos > toscr + 300) {\n";
OX_0daa6395 += "loaded = true;\n";
OX_0daa6395 += "var journal = \"\";\n";
OX_0daa6395 += "var metas = document.getElementsByTagName(\'meta\');\n";
OX_0daa6395 += "var i;\n";
OX_0daa6395 += "for (i = 0; i <"+" metas.length; i++) {\n";
OX_0daa6395 += "if (metas[i].getAttribute(\'name\') == \"citation_journal_title\") {\n";
OX_0daa6395 += "break;\n";
OX_0daa6395 += "}\n";
OX_0daa6395 += "}\n";
OX_0daa6395 += "if (metas[i] != undefined) journal = encodeURIComponent(metas[i].getAttribute(\'content\'));\n";
OX_0daa6395 += "var publisher = \"\";\n";
OX_0daa6395 += "for (i = 0; i <"+" metas.length; i++) {\n";
OX_0daa6395 += "if (metas[i].getAttribute(\'name\') == \"citation_publisher\") {\n";
OX_0daa6395 += "break;\n";
OX_0daa6395 += "}\n";
OX_0daa6395 += "}\n";
OX_0daa6395 += "if (metas[i] != undefined) publisher = encodeURIComponent(metas[i].getAttribute(\'content\'));\n";
OX_0daa6395 += "var sctag = document.createElement(\'script\');\n";
OX_0daa6395 += "var proto = (location.protocol==\'https:\') ? \'https\' : \'http\';\n";
OX_0daa6395 += "var startspace = -1 * toscr;\n";
OX_0daa6395 += "var scrollspace = windowheight;\n";
OX_0daa6395 += "sctag.src = proto + \"://delivery.pbgrd.com/banner/banner-biomed-right-v1.php?doi=10.1186/1472-6882-10-3&clickurl=http://delivery.pbgrd.com/openx/www/delivery/ck.php?oaparams=2__bannerid=168__zoneid=43__cb=dd60da9d8b__doi=10.1186%2F1472-6882-10-3__oadest=&zoneid=43&bannerid=168&pageurl=http%3A%2F%2Fwww.biomedcentral.com%2F1472-6882%2F10%2F3\" + \"&journal=\" + journal + \"&publisher=\" + publisher + \"&startspace=\" + startspace + \"&scrollspace=\" + scrollspace + \"&verty=\" + screen.height;\n";
OX_0daa6395 += "document.getElementById(\"advert-offset\").appendChild(sctag);\n";
OX_0daa6395 += "}\n";
OX_0daa6395 += "}\n";
OX_0daa6395 += "}\n";
OX_0daa6395 += "if (window.addEventListener) {\n";
OX_0daa6395 += "window.addEventListener(\'scroll\', function() { pgload(); }, false);\n";
OX_0daa6395 += "} else if (window.attachEvent) {\n";
OX_0daa6395 += "window.attachEvent(\'onscroll\', function() { pgload(); });\n";
OX_0daa6395 += "}\n";
OX_0daa6395 += "//]]>--><"+"/script><"+"div id=\'beacon_dd60da9d8b\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://delivery.pbgrd.com/openx/www/delivery/lg.php?bannerid=168&amp;campaignid=85&amp;zoneid=43&amp;loc=1&amp;referer=http%3A%2F%2Fwww.biomedcentral.com%2F1472-6882%2F10%2F3&amp;cb=dd60da9d8b&amp;doi=10.1186%2F1472-6882-10-3\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
document.write(OX_0daa6395);
