var OX_f0ffdc04 = '';
OX_f0ffdc04 += "<"+"script type=\'text/javascript\'><"+"!--//<"+"![CDATA[\n";
OX_f0ffdc04 += "var headerheight = 0;\n";
OX_f0ffdc04 += "var naviheight = 0;\n";
OX_f0ffdc04 += "var startspace = 0;\n";
OX_f0ffdc04 += "var scrollspace = 0;\n";
OX_f0ffdc04 += "if (navigator.appName == \"Microsoft Internet Explorer\") {\n";
OX_f0ffdc04 += "var windowheight = window.document.documentElement.clientHeight;\n";
OX_f0ffdc04 += "} else {\n";
OX_f0ffdc04 += "var windowheight = window.innerHeight;\n";
OX_f0ffdc04 += "}\n";
OX_f0ffdc04 += "var headerheight = document.getElementById(\"content\").offsetTop;\n";
OX_f0ffdc04 += "if (document.getElementById(\"box-outline\") == null) {\n";
OX_f0ffdc04 += "var startspace = windowheight -(headerheight+15);\n";
OX_f0ffdc04 += "var scrollspace = windowheight -(headerheight+15);\n";
OX_f0ffdc04 += "} else {\n";
OX_f0ffdc04 += "var naviheight = document.getElementById(\"box-outline1\").offsetTop;\n";
OX_f0ffdc04 += "var startspace = windowheight -(headerheight+15+naviheight);\n";
OX_f0ffdc04 += "var scrollspace = windowheight-(20+naviheight);\n";
OX_f0ffdc04 += "}\n";
OX_f0ffdc04 += "var metas = document.getElementsByTagName(\'meta\');\n";
OX_f0ffdc04 += "var i;\n";
OX_f0ffdc04 += "var journal = \"\";\n";
OX_f0ffdc04 += "for (i = 0; i <"+" metas.length; i++) {\n";
OX_f0ffdc04 += "if (metas[i].getAttribute(\'name\') == \"citation_journal_title\") {\n";
OX_f0ffdc04 += "break;\n";
OX_f0ffdc04 += "}\n";
OX_f0ffdc04 += "}\n";
OX_f0ffdc04 += "if (metas[i] != undefined) journal = encodeURIComponent(metas[i].getAttribute(\'content\'));\n";
OX_f0ffdc04 += "var publisher = \"\";\n";
OX_f0ffdc04 += "for (i = 0; i <"+" metas.length; i++) {\n";
OX_f0ffdc04 += "if (metas[i].getAttribute(\'name\') == \"citation_publisher\") {\n";
OX_f0ffdc04 += "break;\n";
OX_f0ffdc04 += "}\n";
OX_f0ffdc04 += "}\n";
OX_f0ffdc04 += "if (metas[i] != undefined) publisher = encodeURIComponent(metas[i].getAttribute(\'content\'));\n";
OX_f0ffdc04 += "var proto = (location.protocol==\'https:\') ? \'https\' : \'http\';\n";
OX_f0ffdc04 += "var pg_base = proto + \'://delivery.pbgrd.com/images/\';\n";
OX_f0ffdc04 += "var asrand = Math.floor(Math.random()*99999999999);\n";
OX_f0ffdc04 += "var pg_dest = pg_base + \'?project=biomed&amp;asrand=\' + asrand;\n";
OX_f0ffdc04 += "document.write (\'<"+"img src=\"\' + pg_dest + \'\" alt=\"\" width=1 height=1>\');\n";
OX_f0ffdc04 += "document.write (\'<"+"scr\' + \'ipt type=\"text/javascript\" src=\"\' + proto + \'://delivery.pbgrd.com/banner/html-banner-biomed-multispv13.php?doi=10.1186/1472-6882-10-3&clickurl=http://delivery.pbgrd.com/openx/www/delivery/ck.php?oaparams=2__bannerid=103__zoneid=5__cb=c8a115cbdb__doi=10.1186%2F1472-6882-10-3__oadest=&campaign=biomed_newlabels&zoneid=5&bannerid=103&pageurl=http%3A%2F%2Fwww.biomedcentral.com%2F1472-6882%2F10%2F3&bstyle=multi\');\n";
OX_f0ffdc04 += "document.write (\"&journal=\" + journal);\n";
OX_f0ffdc04 += "document.write (\"&publisher=\" + publisher);\n";
OX_f0ffdc04 += "document.write (\"&startspace=\" + startspace);\n";
OX_f0ffdc04 += "document.write (\"&scrollspace=\" + scrollspace);\n";
OX_f0ffdc04 += "document.write (\"&verty=\" + screen.height);\n";
OX_f0ffdc04 += "if (document.getElementById(\"box-outline\") == null) {\n";
OX_f0ffdc04 += "document.write (\"&mode=abstracts\");\n";
OX_f0ffdc04 += "}\n";
OX_f0ffdc04 += "document.write (\'\"><"+"\\/scr\'+\'ipt>\');\n";
OX_f0ffdc04 += "//]]>--><"+"/script><"+"div id=\'beacon_c8a115cbdb\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://delivery.pbgrd.com/openx/www/delivery/lg.php?bannerid=103&amp;campaignid=49&amp;zoneid=5&amp;loc=1&amp;referer=http%3A%2F%2Fwww.biomedcentral.com%2F1472-6882%2F10%2F3&amp;cb=c8a115cbdb&amp;doi=10.1186%2F1472-6882-10-3\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
document.write(OX_f0ffdc04);
